devices:
  depo:
    s_positions:
      full_down: -288
      full_up: 0
    vol_deg_map:
      0: 0
      0.093: 82.305
      0.207: 183.195
      0.212: 187.62
      0.282: 249.57
      0.325: 287.625
      0.392: 346.92
      0.408: 361.08
      0.485: 429.225
      0.498: 440.73
      0.589: 521.265
      0.596: 527.46
      0.649: 574.365
    x_offset: -33
    y_offset: -203
  pH:
    pH_positions:
      full_down: -348
      full_up: 0
    verbose: true
    x_offset: 0
    y_offset: 0
global:
  pi1_address: 192.168.1.11
  pi2_address: 192.168.1.14
stage:
  aux_loc_map:
    acid:
    - -1196
    - 38
    base:
    - -1251
    - -758
    clean:
    - -729
    - -843
    near origin:
    - -918
    - -5
    blot:
    - -146
    - -1091
  cell_loc_map: /Users/notaspy/Desktop/Legolas_textCellLoc-main/cell_map.txt
  home_x_offset: -100
  home_y_offset: -100
