devices:
  depo:
    s_positions:
      full_down: -273
      full_up: 16
      intake: -190
    vol_deg_map:
      0.0: -73
      0.081: 67
      0.209: 157
      0.312: 232
      0.427: 313
      0.499: 390
      0.59: 474
    x_offset: -33
    y_offset: -203
  pH:
    pH_positions:
      full_down: -684
      full_up: -243
    verbose: true
    x_offset: 0
    y_offset: 0
global:
  pi1_address: 192.168.1.11
  pi2_address: 192.168.1.14
stage:
  aux_loc_map:
    acid:
    - -1038
    - -217
    base:
    - -1041
    - -456
    blot:
    - -150
    - -1118
    clean:
    - -729
    - -843
    near origin:
    - -918
    - -5
  cell_loc_map: /Users/notaspy/Desktop/Legolas_textCellLoc-main/cell_map.txt
  home_x_offset: -100
  home_y_offset: -100
