devices:
  depo:
    s_positions:
      full_down: -257
      full_up: 13
    vol_deg_map:
      0.0: -1
      0.091: 114
      0.159: 147
      0.229: 223
      0.304: 265
      0.32: 299
      0.466: 399
      0.485: 432
      0.624: 544
      0.667: 563
      0.753: 641
    x_offset: -62
    y_offset: -189
  pH:
    pH_positions:
      full_down: 413
      full_up: 776
    verbose: true
    x_offset: 0
    y_offset: 0
global:
  pi1_address: 192.168.1.11
  pi2_address: 192.168.1.12
stage:
  aux_loc_map:
    acid:
    - -1251
    - -205
    base:
    - -1251
    - -758
    clean:
    - -1055
    - -428
  cell_loc_map: C:\Users\mlowe\Documents\AlphaImmersion_I_attendedLEGOLAS2023\LEGOLAS
    new4 Scripts\cell_map.txt
  home_x_offset: -100
  home_y_offset: -100
