name: python_3.7.4
channels:
  - defaults
dependencies:
  - python =3.7.4
  - ipykernel=5.1.2
  - numpy=1.16.5
  - scipy=1.3.1
  - pyyaml=5.1.2
  - matplotlib=3.1.1
  - paramiko=3.2.0
  - sv_ttk=2.4.5
  - rpyc=5.3.1
  