devices:
  depo:
    s_positions:
      full_down: -246
      full_down_re: -289
      full_up: -34
    vol_deg_map:
      0.0: -177
      0.193: -8
      0.38: 140
      0.747: 433
    x_offset: -53
    y_offset: -195
  pH:
    pH_positions:
      full_down: 1884
      full_up: 2081
    verbose: true
    x_offset: 0
    y_offset: 0
global:
  pi1_address: 192.168.0.2
  pi2_address: 192.168.0.3
stage:
  aux_loc_map:
    acid:
    - -1313
    - -120
    base:
    - -1326
    - -717
    clean:
    - -1136
    - -421
  cell_loc_map: C:\Users\auror\Desktop\legolas\cell_map.pkl
  home_x_offset: -100
  home_y_offset: -100
